name: package_assets_generator
description: Package assets generator.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  build: ^4.0.4
  path: ^1.9.1

dev_dependencies:
  very_good_analysis: ^10.0.0
