name: pub_score_checker
description: Evaluate the health and quality of a Dart package.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  args: ^2.7.0
  logging: ^1.3.0
  pana: ^0.23.3

dev_dependencies:
  very_good_analysis: ^10.0.0

executables:
  pub_score_checker: pub_score_checker
