name: pub_score_checker
description: Evaluate the health and quality of a Dart package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  pana: any # Using the latest version of `pana` to ensure that the package score computation method is also up-to-date.

dev_dependencies:
  very_good_analysis: ^7.0.0
