name: coverde
description: A CLI for optimizing test execution and manipulating coverage trace files. Optimize tests, validate coverage, filter trace files, and generate HTML reports.
version: 0.3.0+1
homepage: https://github.com/mrverdant13/coverde
repository: https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli
issue_tracker: https://github.com/mrverdant13/coverde/issues
topics:
  - test
  - testing
  - coverage
  - lcov
screenshots:
  - description: Coverage report example (directory)
    path: doc/examples/browser/coverde-report-dir.png
  - description: Coverage report example (file)
    path: doc/examples/browser/coverde-report-file.png
  - description: Coverage check example
    path: doc/examples/terminal/coverde-check-50.png
  - description: Coverage value example
    path: doc/examples/terminal/coverde-value-file-coverage-log-level-line-numbers.png
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  analyzer: ">=8.0.0 <=10.0.0"
  args: ^2.7.0
  code_builder: ^4.11.1
  collection: ^1.19.1
  dart_style: ^3.1.3
  glob: ^2.1.3
  html: ^0.15.6
  http: ^1.6.0
  io: ^1.0.5
  mason_logger: ^0.3.3
  meta: ^1.0.0
  path: ^1.9.1
  process: ^5.0.5
  pub_semver: ^2.2.0
  pubspec_parse: ^1.5.0
  universal_io: ^2.3.1
  yaml: ^3.1.3

dev_dependencies:
  build: ^4.0.3
  build_config: ^1.2.0
  build_runner: ^2.10.5
  build_verify: ^3.1.1
  csslib: ^1.0.2
  mocktail: ^1.0.4
  package_assets_generator:
    git:
      url: https://github.com/mrverdant13/coverde.git
      path: tools/package_assets_generator
      ref: 95ddc13ebb5ff7540e3eec3b83ccd5c53ae5414b
  package_data_generator:
    git:
      url: https://github.com/mrverdant13/coverde.git
      path: tools/package_data_generator
      ref: 95ddc13ebb5ff7540e3eec3b83ccd5c53ae5414b
  test: ^1.29.0
  very_good_analysis: ^10.0.0

executables:
  coverde:
