name: coverde
description: A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.
version: 0.2.0+2
homepage: https://github.com/mrverdant13/coverde
repository: https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli
issue_tracker: https://github.com/mrverdant13/coverde/issues
topics:
  - test
  - testing
  - coverage
  - lcov
screenshots:
  - description: Coverage report example (directory)
    path: doc/report_directory_example.png
  - description: Coverage report example (file)
    path: doc/report_file_example.png
  - description: Coverage check example (passing)
    path: doc/check_result_pass.png
  - description: Coverage check example (failing)
    path: doc/check_result_fail.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  collection: ^1.19.0
  html: ^0.15.4
  io: ^1.0.4
  meta: ^1.16.0
  path: ^1.9.0
  process: ^5.0.2
  pub_updater: ^0.5.0
  universal_io: ^2.2.2

dev_dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  csslib: ^1.0.0
  mocktail: ^1.0.4
  package_assets_generator:
    path: ../package_assets_generator
  package_data_generator:
    path: ../package_data_generator
  pubspec_parse: ^1.3.0
  test: ^1.25.8
  very_good_analysis: ">=6.0.0 <8.0.0"

executables:
  coverde:
